/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Appointment {
  'service' : Service,
  'customerName' : string,
  'status' : AppointmentStatus,
  'date' : Time,
  'phone' : string,
  'timeSlot' : TimeSlot,
}
export interface AppointmentForm {
  'service' : Service,
  'customerName' : string,
  'date' : Time,
  'phone' : string,
  'timeSlot' : TimeSlot,
}
export type AppointmentStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'confirmed' : null };
export type Service = { 'massage' : null } |
  { 'hairStyling' : null } |
  { 'pedicure' : null } |
  { 'haircut' : null } |
  { 'hairColoring' : null } |
  { 'waxing' : null } |
  { 'manicure' : null } |
  { 'threading' : null } |
  { 'facial' : null } |
  { 'bridalMakeup' : null };
export interface Testimonial {
  'name' : string,
  'comment' : string,
  'rating' : bigint,
}
export type Time = bigint;
export interface TimeSlot { 'startTime' : Time, 'endTime' : Time }
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAppointments' : ActorMethod<[], Array<Appointment>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitAppointment' : ActorMethod<[AppointmentForm], undefined>,
  'submitTestimonial' : ActorMethod<[Testimonial], undefined>,
  'updateAppointmentStatus' : ActorMethod<
    [string, AppointmentStatus],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];