/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Service = IDL.Variant({
  'massage' : IDL.Null,
  'hairStyling' : IDL.Null,
  'pedicure' : IDL.Null,
  'haircut' : IDL.Null,
  'hairColoring' : IDL.Null,
  'waxing' : IDL.Null,
  'manicure' : IDL.Null,
  'threading' : IDL.Null,
  'facial' : IDL.Null,
  'bridalMakeup' : IDL.Null,
});
export const AppointmentStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const Time = IDL.Int;
export const TimeSlot = IDL.Record({ 'startTime' : Time, 'endTime' : Time });
export const Appointment = IDL.Record({
  'service' : Service,
  'customerName' : IDL.Text,
  'status' : AppointmentStatus,
  'date' : Time,
  'phone' : IDL.Text,
  'timeSlot' : TimeSlot,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Testimonial = IDL.Record({
  'name' : IDL.Text,
  'comment' : IDL.Text,
  'rating' : IDL.Nat,
});
export const AppointmentForm = IDL.Record({
  'service' : Service,
  'customerName' : IDL.Text,
  'date' : Time,
  'phone' : IDL.Text,
  'timeSlot' : TimeSlot,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitAppointment' : IDL.Func([AppointmentForm], [], []),
  'submitTestimonial' : IDL.Func([Testimonial], [], []),
  'updateAppointmentStatus' : IDL.Func([IDL.Text, AppointmentStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Service = IDL.Variant({
    'massage' : IDL.Null,
    'hairStyling' : IDL.Null,
    'pedicure' : IDL.Null,
    'haircut' : IDL.Null,
    'hairColoring' : IDL.Null,
    'waxing' : IDL.Null,
    'manicure' : IDL.Null,
    'threading' : IDL.Null,
    'facial' : IDL.Null,
    'bridalMakeup' : IDL.Null,
  });
  const AppointmentStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const Time = IDL.Int;
  const TimeSlot = IDL.Record({ 'startTime' : Time, 'endTime' : Time });
  const Appointment = IDL.Record({
    'service' : Service,
    'customerName' : IDL.Text,
    'status' : AppointmentStatus,
    'date' : Time,
    'phone' : IDL.Text,
    'timeSlot' : TimeSlot,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Testimonial = IDL.Record({
    'name' : IDL.Text,
    'comment' : IDL.Text,
    'rating' : IDL.Nat,
  });
  const AppointmentForm = IDL.Record({
    'service' : Service,
    'customerName' : IDL.Text,
    'date' : Time,
    'phone' : IDL.Text,
    'timeSlot' : TimeSlot,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitAppointment' : IDL.Func([AppointmentForm], [], []),
    'submitTestimonial' : IDL.Func([Testimonial], [], []),
    'updateAppointmentStatus' : IDL.Func([IDL.Text, AppointmentStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };